defaults:
  - _self_
  - data: mnist
  - guide: vae
  - model: vae
  - monad: svi
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
tags: ["dev"]
train: False
test: True
ckpt_path: null
optimized_metric: "loss"
seed: 1234
